### ISSUE TITLE
how to get source code for Mumps in my Mac?

### ISSUE THREAD

**Issue by ghost** [coin-or-tools/ThirdParty-Mumps#1]
I am trying to get source code for Mumps in my Mac Pro 2019, but I get error:

    naghmehs-MacBook-Pro:~ naghmeh$ cd COIN-1.8
naghmehs-MacBook-Pro:COIN-1.8 naghmeh$ cd ThirdParty/Mumps
naghmehs-MacBook-Pro:Mumps naghmeh$ ./get.Mumps
Utility wget not found in your PATH.
Using ftp command instead.
 
Running script for downloading the source code for MUMPS
 
Downloading the source code from ...
./get.Mumps: line 31: ftp: command not found
naghmehs-MacBook-Pro:Mumps naghmeh$

**Comment by svigerske** [comment]
This `COIN-1.8` that you use (I don't really know what that is), seems to use an old version of get.Mumps. You can try replacing that one with the current one: https://raw.githubusercontent.com/coin-or-tools/ThirdParty-Mumps/master/get.Mumps

**Comment by ghost** [comment]
how I can replace?

**Comment by svigerske** [comment]
Really?
```
rm get.Mumps
curl -O https://raw.githubusercontent.com/coin-or-tools/ThirdParty-Mumps/master/get.Mumps
```

**Comment by ghost** [comment]
ok I fixed the problem I needed to get wget.

**Comment by tkralphs** [comment]
FYI, I guess you are using the COIN-OR-OptimizationSuite stable version 1.8. We are in the process of some changes to the build system, moving all projects to management by git, etc. The stable version of the optimization suite has not been updated in some time and some projects are no longer managed in SVN. The most recent stable version of Mumps, for example, is 1.6 and the optimization suite is still on 1.5. For now, please take a look at [coinbrew](https://github.com/coin-or/coinbrew) and use it get the most recent versions of whatever specific projects you are interested in. I will try to update the Dependencies and documentation as soon as I can.

**Comment by naghmeh6** [comment]
yes, that's right I am installing Coin-or. I installed required packages but I have a problem with Compile it . 
following steps in here:
https://ma.juii.net/blog/install-coin-or

**Comment by ghost** [comment]
> FYI, I guess you are using the COIN-OR-OptimizationSuite stable version 1.8. We are in the process of some changes to the build system, moving all projects to management by git, etc. The stable version of the optimization suite has not been updated in some time and some projects are no longer managed in SVN. The most recent stable version of Mumps, for example, is 1.6 and the optimization suite is still on 1.5. For now, please take a look at [coinbrew](https://github.com/coin-or/coinbrew) and use it get the most recent versions of whatever specific projects you are interested in. I will try to update the Dependencies and documentation as soon as I can.

yes, that's right I am installing Coin-or. I installed required packages but I have a problem with Compile it . 
following steps in here:
https://ma.juii.net/blog/install-coin-or

**Comment by ghost** [comment]
> > FYI, I guess you are using the COIN-OR-OptimizationSuite stable version 1.8. We are in the process of some changes to the build system, moving all projects to management by git, etc. The stable version of the optimization suite has not been updated in some time and some projects are no longer managed in SVN. The most recent stable version of Mumps, for example, is 1.6 and the optimization suite is still on 1.5. For now, please take a look at [coinbrew](https://github.com/coin-or/coinbrew) and use it get the most recent versions of whatever specific projects you are interested in. I will try to update the Dependencies and documentation as soon as I can.
> 
> yes, that's right I am installing Coin-or. I installed required packages but I have a problem with Compile it .
> following steps in here:
> https://ma.juii.net/blog/install-coin-or

Do you think problem is what you explained? I get this error:
collect2: fatal error: ld terminated with signal 11 [Segmentation fault: 11]
compilation terminated.
ld: unexpected token: !tapi-tbd-v3 file '/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib/libm.tbd' for architecture x86_64
make[1]: *** [libcoinblas.la] Error 1
make: *** [all-recursive] Error 1

**Comment by tkralphs** [comment]
I would need to see more of the output in order to know what's going on, but you should never see a segmentation fault like that during a build. That looks like it's not a build failure, but an actual bug in the linker. I've never seen that.

If you tell me what you're really after, I can try to help. There are homebrew recipes for building some of the projects on OS X and that is the best way. 

I don't know why people ask questions on a blog of some random person instead of here! Things change and instructions on a five year old blog post are unlikely to be correct.

In any case, please try with the most up-to-date build processes. I'm happy to answer questions while we're in the period of transition.

**Comment by svigerske** [comment]
ThirdParty-Mumps is also not the proper place to discuss why ld crashed.
Just pasting this into some search engine gives plenty of hits, something may explain how to fix this computer.
