### ISSUE TITLE
MUMPS URL http://mumps.enseeiht.fr/MUMPS_5.5.1.tar.gz is dead

### ISSUE THREAD

**Issue by yurivict** [coin-or-tools/ThirdParty-Mumps#10]
Could you please either fix it, or remove it?

**Comment by svigerske** [comment]
Where is this URL referenced?

On stable/3.0, I only found one place in an `echo` statement, but no place this is actually used.
The last release is still using 5.5.0.

The preferred choice by the `get` script is to download from our copy of the packages at GitHub anyway.

**Comment by yurivict** [comment]
[here](https://github.com/coin-or-tools/ThirdParty-Mumps/blob/stable/3.0/get.Mumps#L40)

**Comment by svigerske** [comment]
This is `mumps-solver.org`. Probably this forwards to `mumps.enseeiht.fr` and some day the MUMPS people may get their webserver running again.

The MUMPS webservers comes and goes. I don't understand what they are doing, but it is the reason why we store a copy of the MUMPS source packages in the [gh-pages branch of this repo](https://github.com/coin-or-tools/ThirdParty-Mumps/tree/gh-pages ) and the `get.Mumps` script is first trying to download from `http://coin-or-tools.github.io/ThirdParty-Mumps/`.    
Only if this fails does it try to download from `mumps-solver.org`. At times the MUMPS server is up, this will work. At times it doesn't, it will fail. If I remove this trial, it will just always fail. So I see no use in removing this secondary option.
