### ISSUE TITLE
Compiling Mumps to shared library on windows fails

### ISSUE THREAD

**Issue by aymanhab** [coin-or-tools/ThirdParty-Mumps#12]
Following the instructions to build mumps into a shared library on windows I'm stuck as the recommended fortran compiler (ifx) doesn't support shared libraries, and I need that (dll) for upsteam usage. Any pointer to a current setup that creates one or published mumps shared libraries native to windows? I understand this may belong better into a discussion forum, if so I'd appreciate a pointer. Thanks for the great work and for the support.

**Comment by svigerske** [comment]
The Windows binaries attached to [Ipopt releases](https://github.com/coin-or/Ipopt/releases) include MUMPS DLLs, also with corresponding `lib` file.

Otherwise, maybe you can compile the MUMPS objects first, but then call a different linker to put them together into a DLL.

**Comment by aymanhab** [comment]
Thanks much that worked out great 👍  luckily the stack used to build this windows distribution (lapack, mumps, metis, ipopt) is exactly what we needed. The only hiccup downstream is that the ipopt distribution doesn't have a cmake folder to enable the CMake build system to extract the compile/link options from the distro. Will it be possible to include that in the distribution or point me to how to generate it? Thanks again for your support and please feel free to close this issue.

**Comment by svigerske** [comment]
The build system has been updated that it should work with `ifx` now, at least on Windows (msys2). Use `--enable-msvc` for configure as well.

Currently, there is no plan to create some cmake folder for Ipopt.
