### ISSUE TITLE
single precision 

### ISSUE THREAD

**Issue by pqy1010** [coin-or-tools/ThirdParty-Mumps#5]
hi @svigerske  i am trying to use single precision floats for my project ,and i have read [Single precision use #403 ](https://github.com/coin-or/Ipopt/issues/403)but now i am stuck at build ThirdParty-Mumps to single precision version, and i can't find good answer for this question , i don't know if their is any other good way to build ThirdParty-Mumps with single precision floats ,so i have to ask for your help.

i replaced  all "dmumps" with "smumps" in MakeFile.in file when build ThirdParty-Mumps ,and it's looks like build success. but when i build my project  it's failed with information  "/usr/bin/ld: /usr/local/lib/libipopt.so: undefined reference to `smumps_c'
",so ,i guess there is something wrong when build  ThirdParty-Mumps  with single precision floats.

**Comment by svigerske** [comment]
`MUMPS_ARITH` needs to be defined to `MUMPS_ARITH_s` instead of `MUMPS_ARITH_d` to get smumps_c, I believe.

I never tried single-precision with MUMPS 4.10. Note that branch `mumps5` of `ThirdParty-Mumps` is setup for building a single-precision version of Mumps.

**Comment by pqy1010** [comment]
mumps5 is good, It was build success,Thank you very much.
