### ISSUE TITLE
About the license

### ISSUE THREAD

**Issue by snio89** [coin-or-tools/ThirdParty-Mumps#6]
I'd just tried to install CBC from its source and reached to this third-party package. I wanted to know what this package is and now have a question about the license.

The front page describes that `ThirdParty-Mumps` retrieves and builds `MUMPS` 4.10.0. And `MUMPS` has [CeCILL-C license](http://mumps.enseeiht.fr/doc/userguide_5.4.0.pdf), French version of GPL. As I know, Eclipse Public License and GPL are [incompatible](https://www.eclipse.org/legal/epl-2.0/faq.php#h.sfzscklic49g). It seems like this package cannot be [licensed](https://github.com/coin-or-tools/ThirdParty-Mumps/blob/master/README.md) under EPL v1.0. I don't have any relationship with both packages but just wants to identify the problem.

**Comment by svigerske** [comment]
All that ThirdParty-Mumps provides is a buildsystem for MUMPS. It doesn't include any MUMPS source code.

I may be naive, but like to believe that ThirdParty-Mumps qualifies neither as "derivative work" nor "work based on" MUMPS as mentioned in this EPL FAQ.

**Comment by snio89** [comment]
I agree with it and close this issue. Sorry for bothering.
